### PR TITLE
feature: retrieve disk usage via _disk_usage API

### PR DESCRIPTION
**Pull request by ilvar**
Add the new [_disk_usage](https://www.elastic.co/guide/en/elasticsearch/reference/7.15/indices-disk-usage.html) endpoint for Elasticsearch

### CODE REVIEW

**Comment by pickypg** [comment]
I created an issue with the ES team to see if they might consider a `GET` request variant that drops the `flush` parameter entirely.

https://github.com/elastic/elasticsearch/issues/82594

**Review by pickypg — CHANGES_REQUESTED** [review]
Blocked by https://github.com/elastic/elasticsearch/issues/82594.

**Comment by ilvar** [comment]
@pickypg I've signed CLA after creating the PR though looks like it's not propagated. Re-signed today; double checked than it matches full name and email in my git config

**Comment by pickypg** [comment]
Thanks @ilvar. It looks like the CLA checker is happy now. Now we just have to wait for the ES team to decide if they want to add a `GET` version of this API and, if so, one of us will need to tweak the version(s).

**Comment by pickypg** [comment]
It looks like the ES team does not want to add this API as a `GET`. Closing this one out. Thanks for the try though!

**Pull request closed without merging**
