### PR TITLE
Update README.md - fixed typos, formatting, etc

### PR DESCRIPTION
**Pull request by RicardoGralhoz**

### CODE REVIEW

**Comment by RicardoGralhoz** [comment]
> ❌ Author of the following commits did not sign a [Contributor Agreement](https://www.elastic.co/contributor-agreement):
> [e204660](https://github.com/elastic/support-diagnostics/commit/e2046602254e6a59e8c50f44c41645c9f4f074e3)
> 
> Please, read and sign the above mentioned agreement if you want to contribute to this project

I did try to sign it multiple times; got some issues, though!

**Comment by pickypg** [comment]
Hi @RicardoGralhoz,

Thanks for this PR. We waited too long to merge this and I am sorry for that. However, we have three options:

1. We can wait for you to rebase it on `main` (from `master`) to limit the incoming commits.
2. I can just copy the changes into my own PR and have you review it.
3. I can just copy the changes without waiting.

What do you think? I know its been sitting here for awhile, but in the interest of closing this out, let's say by the end of February let's make a decision?

**Comment by RicardoGralhoz** [comment]
> 1. We can wait for you to rebase it on `main` (from `master`) to limit the incoming commits.

Is this something I can do using GitHub GUI? Could you give me the steps to try this option?

**Comment by pickypg** [comment]
> Is this something I can do using GitHub GUI?

Unfortunately not.

> Could you give me the steps to try this option?

I think so. There's two options for you to do it:

1. Simply open up the commit that matters (https://github.com/elastic/support-diagnostics/pull/455/commits/e2046602254e6a59e8c50f44c41645c9f4f074e3) and re-make the same changes against `main` (https://github.com/elastic/support-diagnostics/edit/main/README.md).
    - This is definitely going to be easier and faster if you're unfamiliar with Git.
2. Follow these new few steps:
    - If you have never used Git, I _strongly_ suggest just copy/pasting your changes across because it will be a lot faster and a lot less frustrating for you.

It looks like you did this from GitHub's UI based on the branch's name, so the first thing you'd have to do is to "clone" [your repository fork](https://github.com/RicardoGralhoz/support-diagnostics) to your local machine to clean it up. If by some chance you had it checked out locally already, you'll want to run (assuming `origin` is your repository, which it probably would be):

```
git checkout patch-1
git pull origin patch-1
```

If you just cloned (downloaded via git) the repository, you'd do:

```
cd directory/to/work
git clone git@github.com:RicardoGralhoz/support-diagnostics.git
cd support-diagnostics
git checkout patch-1
```

You have 9 commits to "add" to main here in this pull request, but only one of them that matters is from you (https://github.com/elastic/support-diagnostics/pull/455/commits/e2046602254e6a59e8c50f44c41645c9f4f074e3), so you want to throw away the rest (including the final merge that you likely did from the UI):

image

Locally, you can run `git rebase` (be careful in here, it can make your life very frustrating):

```
$ git rebase -i HEAD~9
```

This will look something like

```
pick a406459 Monitoring input cloud (#448)
pick 5c0fd54 Rollback README due to deployment issues. (#449)
pick 01bcc84 Commenting for diags.yml, removal of unused settings (#451)
pick 41c5fe9 Interactive URL validation fix
pick 464fe62 Update README.md (#445)
pick ccb8542 Add link to the latest version of the diagnostic (#453)
pick e204660 Update README.md - fixed typos, formatting, etc
pick 07c35f8 Fix downloading-and-installing readme section (#446)
pick 9fb4645 Merge branch 'master' into patch-1
```

Change it to look like this (in `vi`, hit `i` for "interactive" mode and escape to exit interactive mode):

```
d a406459 Monitoring input cloud (#448)
d 5c0fd54 Rollback README due to deployment issues. (#449)
d 01bcc84 Commenting for diags.yml, removal of unused settings (#451)
d 41c5fe9 Interactive URL validation fix
d 464fe62 Update README.md (#445)
d ccb8542 Add link to the latest version of the diagnostic (#453)
pick e204660 Update README.md - fixed typos, formatting, etc
d 07c35f8 Fix downloading-and-installing readme section (#446)
d 9fb4645 Merge branch 'master' into patch-1
```

This could trigger a series of "conflicts" because you may have fixed a typo in a commit introduced being `d`ropped.

Save the file (`[Escape]:wq[Enter]` if using the default vi editor).

Finally, push your changes back up GitHub. This will require `-f` for "force push" due to the rebase command usage:

```
git push origin patch-1 -f
```

**Comment by RicardoGralhoz** [comment]
> 2 I can just copy the changes into my own PR and have you review it.
> 3 I can just copy the changes without waiting.

Thanks, @pickypg , if you have some time you can go ahead and try options 2 or 3.

**Comment by pickypg** [comment]
Closing in favor of https://github.com/elastic/support-diagnostics/pull/475. /cc @RicardoGralhoz

**Pull request closed without merging**
