### PR TITLE
Wrong package path to ScrubApp

### PR DESCRIPTION
**Pull request by lastnico**
Fix the packages in SH & BAT scripts

### CODE REVIEW

**Comment by elasticcla** [comment]
Hi @lastnico, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in your Git [commit](https://github.com/elastic/support-diagnostics/pull/273.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by lastnico** [comment]
I've just signed, afterwards, the Contributor Agreement, so if you can relaunch the checks on this pull request, that would be cool.

**Comment by lastnico** [comment]
Ah, damn it, i've used the default proposed author on my IDE, which is not similar to my Github account. I guess I'll need to redo all to change it (it's not a proper email address).

**Comment by nemonster** [comment]
I'm going to go ahead and approve this despite the CLA check since I could have just gone back and redone it myself and it's not anything inherently risky or compromising.

**Comment by nemonster** [comment]
@lastnico When you get your CLA issue fixed, keep in mind that we'd like to see an issue that corresponds the pull request as well so we can track it better. Thanks for the patch!

**Comment by pickypg** [comment]
@lastnico You could also rewrite your commits and do a force push with the proper author.

**Pull request merged**
