### PR TITLE
[Kibana api] add stack monitoring health api

### PR DESCRIPTION
**Pull request by klacabane**
### Summary
Add a rest call to the [stack monitoring Health endpoint](https://github.com/elastic/kibana/tree/main/x-pack/plugins/monitoring/server/routes/api/v1/_health)

### Testing
- `mvn package`
- `unzip target/diagnostics-8.4.1-SNAPSHOT-dist.zip`
- `./target/diagnostics-8.4.1-SNAPSHOT-dist/diagnostics.sh --type kibana-api --host localhost --port 5601 --output ~/OUTPUT_PATH -u elastic -p`
- navigate to OUTPUT_PATH and verify `kibana_stack_monitoring_health.json` is populated

### CODE REVIEW

**Review by miltonhultgren — APPROVED** [review]
Looks good, looks similar to the other APIs and the version looks correct

**Comment by klacabane** [comment]
@elastic/innovation-eng I don't have any permissions here, could you please have a look :) ?

**Comment by cory-fair** [comment]
@klacabane I'll bring this up on grooming this week so the team can get eyes on it.

**Comment by klacabane** [comment]
@cory-fair any updates on this ?

**Review by PhaedrusTheGreek — APPROVED** [review]
LGTM

**Pull request merged**
